name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # Se ejecuta cada hora
  workflow_dispatch:               # Permite ejecución manual
  push: 
    branches: 
      - master
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Usa la última versión de actions/checkout
      
      - name: Gather Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nisamov
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 4
          plugin_repositories_starred: 0
          repositories_forks: yes

      # Realiza el commit incluso si no hay cambios (commit vacío)
      - name: Commit and push README.md
        run: |
          git config --local user.email "aaa.002.0a0b@gmail.com"
          git config --local user.name "Nisamov"
          git add README.md
          git commit --allow-empty -m "Actualización automática de estadísticas"
          git push
