name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]  # Ejecuta el workflow cada hora
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub
  push: 
    branches: 
      - master
      - main  # Ejecuta el workflow al hacer push en las ramas "main" o "master"

jobs:
  github-metrics:
    runs-on: ubuntu-latest  # Ejecuta el job en un runner de Ubuntu

    permissions:
      contents: write  # Permisos necesarios para escribir en el repositorio

    steps:
      # Paso 1: Usar la última versión de actions/checkout para asegurarnos de usar Node.js 20
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualizado a v4, que usa Node.js 20
      
      # Paso 2: Usar la acción de metrics
      - name: Gather Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # Token que debe estar configurado en los Secrets del repositorio
          user: Nisamov
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 4
          plugin_repositories_starred: 0
          repositories_forks: yes

      # Paso 3: Configurar y hacer commit de los cambios en el README.md
      - name: Commit and push updated README.md
        run: |
          git config --local user.email "aaa.002.0a0b@gmail.com"
          git config --local user.name "Nisamov"
          git add README.md
          git commit -m "Actualización automática de estadísticas"
          git push
