name: Actualizar README.md

on:
  schedule:
    - cron: '0 0 * * *'  # Cada día a la medianoche
    - cron: '0 12 * * *'  # Cada día al mediodía
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Obtener consejo del archivo
        id: get_advice
        run: |
          shuf -n 1 consejos.md > advice.txt
          echo "::set-output name=advice::$(<advice.txt)"

      - name: Resumen de Commits
        id: commit_summary
        run: |
          today=$(date +%Y-%m-%d)
          commits=$(git log --since="$today 00:00:00" --until="$today 23:59:59" --oneline | wc -l)
          lines_updated=$(git log --since="$today 00:00:00" --until="$today 23:59:59" --numstat | awk '{ total += $1 + $2 } END { print total }')
          echo "::set-output name=commits::$commits"
          echo "::set-output name=lines_updated::$lines_updated"

      - name: Actualizar README
        run: |
          current_time=$(date +%H)
          if [ "$current_time" -eq "00" ]; then
            sed -i "/<!--Cita del Día-->/r advice.txt" README.md
          elif [ "$current_time" -eq "12" ]; then
            sed -i "s/<número de líneas actualizadas>/${{ steps.commit_summary.outputs.lines_updated }}/" README.md
            sed -i "s/<número de commits>/${{ steps.commit_summary.outputs.commits }}/" README.md
          fi

      - name: Commit y push del README actualizado
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config --local user.name "Nisamov"
          git config --local user.email "aaa.002.0a0b@gmail.com"
          git add README.md || echo "No changes to commit"
          git commit -m "Actualizar README.md" || echo "No hay cambios para confirmar"
          git push origin main