name: Actualizar README.md

on:
  schedule:
    - cron: '0 0 * * *'  # Cada día a la medianoche
    - cron: '0 12 * * *'  # Cada día al mediodía
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Obtener consejo del archivo
        run: |
          shuf -n 1 consejos.md > advice.txt
          echo "advice=$(<advice.txt)" >> $GITHUB_ENV

      - name: Resumen de Commits
        run: |
          today=$(date +%Y-%m-%d)
          commits=$(git log --since="$today 00:00:00" --until="$today 23:59:59" --oneline | wc -l)
          lines_updated=$(git log --since="$today 00:00:00" --until="$today 23:59:59" --numstat | awk '{ total += $1 + $2 } END { print total }')
          echo "commits=$commits" >> $GITHUB_ENV
          echo "lines_updated=$lines_updated" >> $GITHUB_ENV

      - name: Actualizar README
        run: |
          current_time=$(date +%H)
          if [ "$current_time" -eq "00" ]; then
            sed -i "/<!--Cita del Día-->/r advice.txt" README.md
          elif [ "$current_time" -eq "12" ]; then
            sed -i "s/<número de líneas actualizadas>/${{ env.lines_updated }}/" README.md
            sed -i "s/<número de commits>/${{ env.commits }}/" README.md
          fi

      - name: Eliminar archivo temporal
        run: rm advice.txt

      - name: Verificar y confirmar cambios
        run: |
          if git diff --quiet; then
            echo "No changes to commit";
          else
            git add README.md
            git commit -m "Actualizar README.md con consejo diario"
            git push https://x-access-token:${{ secrets.METRICS_TOKEN }}@github.com/${{ github.repository }}.git
          fi
