name: Metrics
on:
  schedule: 
    - cron: '0 0 * * *'  # Cada día a la medianoche
    - cron: '0 12 * * *'  # Cada día al mediodía
  workflow_dispatch:  # Permite ejecución manual
  push: 
    branches: 
      - master
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Usa la última versión de actions/checkout
      
      - name: Gather Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nisamov
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 4
          plugin_repositories_starred: 0
          repositories_forks: yes

      - name: Pull the latest changes from the remote repository
        run: |
          git pull origin main

      - name: Select random advice and insert it into fichero1.md
        run: |
          # Seleccionar una frase aleatoria desde listaconsejos.md
          consejo=$(shuf -n 1 listaconsejos.md)
          
          # Insertar la frase justo después del marcador en fichero1.md
          sed -i '/<!-- RANDOM_ADVICE -->/a '"$consejo"'' fichero1.md

      - name: Copy the appropriate markdown file to README.md
        run: |
          current_hour=$(date +'%H')  # Obtener la hora actual
          if [ $((current_hour % 2)) -eq 0 ]; then
            cp fichero1.md README.md
          else
             fichero2.md README.md
          fi
        

      - name: Force commit and push README.md
        run: |
          git config --local user.email "aaa.002.0a0b@gmail.com"
          git config --local user.name "Nisamov"
          git add README.md || echo "No changes to commit"
          git commit --allow-empty -m "Actualización automática de contenido"
          git push origin main
