name: Update Version in README

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Get the latest release version
      id: get_version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

    - name: Update README.md with new version
      run: |
        sed -i "s/!!aqui>> [0-9]\+\.[0-9]\+\.[0-9]\+/0.0.1 ${{ env.VERSION }}/g" README.md

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update version to ${{ env.VERSION }}"
        git push
